export const APP_FONTS = {
  InterMedium: require("../../assets/fonts/Inter-Medium.ttf"),
  InterSemiBold: require("../../assets/fonts/Inter-SemiBold.ttf"),
  LatoRegular: require("../../assets/fonts/Lato-Regular.ttf"),
  LatoBold: require("../../assets/fonts/Lato-Bold.ttf"),
  LatoSemiBold: require("../../assets/fonts/Lato-SemiBold.ttf"),
  PoppinsBold: require("../../assets/fonts/Poppins-Bold.ttf"),
  PoppinsRegular: require("../../assets/fonts/Poppins-Regular.otf"),
  PoppinsMedium: require("../../assets/fonts/Poppins-Medium.ttf"),
  PoppinsSemiBold: require("../../assets/fonts/Poppins-SemiBold.otf"),
  RobotoRegular: require("../../assets/fonts/Roboto-Regular.ttf"),
  RobotoBold: require("../../assets/fonts/Roboto-Bold.ttf"),
  DMSansBold: require("../../assets/fonts/DMSans-Bold.ttf"),
  DMSansMedium: require("../../assets/fonts/DMSans-Medium.ttf"),
  MontrealRegular: require("../../assets/fonts/Montreal-Regular.otf"),
  MontrealSemiBold: require("../../assets/fonts/Montreal-SemiBold.otf"),
  MontrealMedium: require("../../assets/fonts/Montreal-Medium.otf"),
  MontrealBold: require("../../assets/fonts/Montreal-Bold.otf"),
};
